x-awslogs-options: &awslogs-options
  awslogs-region: ap-northeast-1
  awslogs-create-group: 'true'
  tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}'

services:
  web:
    image: WEB_IMAGE_FQIN_GOES_HERE
    environment:
      NGINX_WORKER_PROCESSES: ${WEB_NGINX_WORKER_PROCESSES:?}
      NGINX_WORKER_RLIMIT_NOFILE: ${WEB_NGINX_WORKER_RLIMIT_NOFILE:?}
      NGINX_WORKER_CONNECTIONS: ${WEB_NGINX_WORKER_CONNECTIONS:?}
      NGINX_FASTCGI_PASS: app:9000
      NGINX_FASTCGI_DOCUMENT_ROOT: /opt/app/public
    ports:
      - 80:8080
    depends_on:
      - app
    restart: always
    logging:
      driver: awslogs
      options:
        <<: *awslogs-options
        awslogs-group: /eb-test/${ENVIRONMENT}/web
        awslogs-datetime-format: '%Y-%m-%dT%H:%M:%S%z'

  app:
    image: APP_IMAGE_FQIN_GOES_HERE
    env_file:
      - .env
    expose:
      - 9000
    restart: always
    logging:
      driver: awslogs
      options:
        <<: *awslogs-options
        awslogs-group: /eb-test/${ENVIRONMENT}/app
        awslogs-datetime-format: '%Y-%m-%dT%H:%M:%S.%f%z'
