# cspell:ignore errexit, nounset, FQIN
---
version: '3'

set:
  - errexit
  - nounset
  - pipefail

tasks:
  build:live:*:
    requires:
      vars:
        - FQIN
    cmd: docker build --file {{index .MATCH 0}}/Dockerfile --target live --tag {{.FQIN}} ..

  build:live:
    deps:
      - task: build:live:web
        vars:
          FQIN: '{{.FQIN_WEB}}'
      - task: build:live:app
        vars:
          FQIN: '{{.FQIN_APP}}'
    cmd: | #.sh
      yq \
          '.services.web.image = "{{.FQIN_WEB}}" | .services.app.image = "{{.FQIN_APP}}"' \
          ../compose.live.template.yaml \
        > ../docker-compose.yaml
